name: MR Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v7

      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: changes
        with:
          filters: |
            code:
              - 'Sources/**'
              - 'Tests/**'
              - 'Package.swift'
              - 'Package.resolved'

      - name: xcode-select
        if: steps.changes.outputs.code == 'true'
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Build
        if: steps.changes.outputs.code == 'true'
        run: swift build -Xswiftc -warnings-as-errors

      - name: Test
        if: steps.changes.outputs.code == 'true'
        run: swift test -Xswiftc -warnings-as-errors
